Edited some files

diff --git a/shell-scripts/arch_linux_cleaner b/shell-scripts/arch_linux_cleaner
--- a/shell-scripts/arch_linux_cleaner
+++ b/shell-scripts/arch_linux_cleaner
@@ -44,5 +44,11 @@ if [[ -z $run_module ]]; then
   clear_repl_history
   clear_bash_history
 else
-  $run_module
+  declare -f $run_module > /dev/null
+
+  if [[ $? == "0" ]]; then
+    $run_module
+  else
+    echo "Module not found!"
+  fi
 fi
diff --git a/shell-scripts/menu_script b/shell-scripts/menu_script
--- a/shell-scripts/menu_script
+++ b/shell-scripts/menu_script
@@ -1,36 +1,38 @@
 #!/bin/bash
 
-# case-menu
+# case menu
 
 clear
-echo "
-
-Please Select:
+echo "Please select:
 A. Display System Information
 B. Display Disk Space
 C. Display Home Space Utilization
-Q. Quit
-"
+Q. Quit"
 read -p "Enter selection [A, B, C or Q] > "
 
 case $REPLY in
-  q|Q ) echo "Program terminated."
-        exit
-        ;;
-  a|A ) echo "Hostname: $HOSTNAME"
-        uptime
-        ;;
-  b|B ) df -h
-        ;;
-  c|C ) if [[ $(id -u) -eq 0 ]]; then
-          echo "Home Space Utilization (All Users)"
-          du -sh /home/*
-        else
-          echo "Home Space Utilization ($USER)"
-          du -sh $HOME
-        fi
-        ;;
-    * ) echo "Invalid entry" >&2
-        exit 1
-        ;;
+  q|Q)
+      echo "Program terminated."
+      exit
+      ;;
+  a|A)
+      echo "Hostname: $HOSTNAME"
+      uptime
+      ;;
+  b|B)
+      df -h
+      ;;
+  c|C)
+      if [[ $(id -u) -eq 0 ]]; then
+        echo "Home Space Utilization (All Users)"
+        du -sh /home/*
+      else
+        echo "Home Space Utilization ($USER)"
+        du -sh $HOME
+      fi
+      ;;
+  *)
+    echo "Invalid entry" >&2
+    exit 1
+    ;;
 esac
